# Generated by Django 4.1.1 on 2022-10-19 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicacionRedes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('redsocial', models.TextField()),
                ('fecha_creacion', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('link', models.TextField()),
                ('fecha_creacion', models.DateField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='noticia',
            name='contenido',
            field=models.TextField(),
        ),
    ]
